### PR TITLE
Fixed issue with Windows home path

### PR DESCRIPTION
**Pull request by simon-p-r**
Hi

This is a small fix to remove home path which value doesn't include the actual drive of where home is.  I also updated Travis.

Thanks
Simon

### CODE REVIEW

**Comment by simon-p-r** [comment]
Had to remove node 0.8 as travis complaining.

**Comment by eugeneware** [comment]
Thanks @simon-p-r for the PR. Have merged and published. Also I've added you as a committer/contributor under the spirit of [OPEN Open Source](http://openopensource.org/). Cheers!

**Comment by simon-p-r** [comment]
Thanks @eugeneware are you willing to accept other PRs as I see some issues.  Maybe extending methods to include setting and deleting values plus overriding globals with local config would be useful.

**Comment by eugeneware** [comment]
Hi @simon-p-r - absolutely!

**Pull request merged**
